/**
 * Shared postflop feature encoder (ported from gto-poker-overlay).
 *
 * Everything is computed DETERMINISTICALLY from the hand evaluator and a
 * fixed-seed equity estimator (no Math.random), so encodeSpot() is a pure
 * function of the spot — identical at training time and inference time.
 */

import { CardId, createDeck, removeCards, rankOf, suitOf } from "./cards";
import { evaluateHand, HAND_CATEGORY } from "./hand-eval";

export interface Spot {
  holeCards: [CardId, CardId];
  board: CardId[];
  street: "flop" | "turn" | "river";
  heroPos: "IP" | "OOP";
  facingBet: boolean;
  toCallFrac: number;
  offeredSizeFrac: number;
  canCheck: boolean;
  canBet: boolean;
  canCall: boolean;
  canRaise: boolean;
  canFold: boolean;
  threeBetPot: boolean;
  isPreflopAggressor?: boolean;
  facedRaiseThisStreet?: boolean;
  streetBetCount?: number;
}

const CATEGORY_COUNT = 9; // HIGH_CARD(0) .. STRAIGHT_FLUSH(8)
export const FEATURE_DIM = 51;

export const ACTION_MASK_OFFSET = 32;
export const NUM_ACTIONS = 5;
export const ACTIONS = ["fold", "check", "call", "bet", "raise"] as const;
export type ActionClass = (typeof ACTIONS)[number];

export const SIZE_BUCKET_FRACS = [0.4, 0.66, 0.85, 1.25, 2.0] as const;
export const NUM_SIZE_BUCKETS = SIZE_BUCKET_FRACS.length;
const SIZE_EDGES = [0.53, 0.755, 1.05, 1.625];

export function sizeBucketOf(frac: number): number {
  for (let i = 0; i < SIZE_EDGES.length; i++) {
    if (frac <= SIZE_EDGES[i]) return i;
  }
  return SIZE_EDGES.length;
}

const clamp = (x: number, lo: number, hi: number): number =>
  x < lo ? lo : x > hi ? hi : x;

/**
 * Deterministic equity-vs-random estimate using the same evaluator as the
 * rest of the codebase. NO RNG: it walks a fixed pseudo-random-but-
 * deterministic sequence generated by a fixed-seed LCG, so the result is a
 * pure function of the spot. River is computed exactly.
 */
const EQUITY_SAMPLES = 400;

export function deterministicEquity(
  hole: [CardId, CardId],
  board: CardId[]
): number {
  if (board.length < 3) {
    const r1 = rankOf(hole[0]);
    const r2 = rankOf(hole[1]);
    return clamp(0.35 + (r1 + r2) / 48 + (r1 === r2 ? 0.1 : 0), 0, 1);
  }

  const known = [hole[0], hole[1], ...board];
  const deck = removeCards(createDeck(), known);
  const n = deck.length;
  const need = 5 - board.length;

  let win = 0;
  let tie = 0;
  let total = 0;

  if (need === 0) {
    const heroRank = evaluateHand([hole[0], hole[1], ...board]);
    for (let i = 0; i < n; i++) {
      for (let j = i + 1; j < n; j++) {
        const vr = evaluateHand([deck[i], deck[j], ...board]);
        if (heroRank > vr) win++;
        else if (heroRank === vr) tie++;
        total++;
      }
    }
    return total === 0 ? 0.5 : (win + tie * 0.5) / total;
  }

  let seed = 0x9e3779b9 >>> 0;
  for (const c of known) seed = (Math.imul(seed ^ c, 0x85ebca6b) + 1) >>> 0;
  const next = () => {
    seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
    return seed / 0x100000000;
  };
  const pick = () => deck[(next() * n) | 0];

  for (let s = 0; s < EQUITY_SAMPLES; s++) {
    const va = pick();
    let vb = pick();
    let guard = 0;
    while (vb === va && guard++ < 8) vb = pick();
    if (vb === va) continue;

    const runout: CardId[] = [];
    let g2 = 0;
    while (runout.length < need && g2++ < 32) {
      const r = pick();
      if (r === va || r === vb || runout.includes(r)) continue;
      runout.push(r);
    }
    if (runout.length < need) continue;

    const full = [...board, ...runout];
    const heroRank = evaluateHand([hole[0], hole[1], ...full]);
    const vr = evaluateHand([va, vb, ...full]);
    if (heroRank > vr) win++;
    else if (heroRank === vr) tie++;
    total++;
  }
  return total === 0 ? 0.5 : (win + tie * 0.5) / total;
}

interface HeroExtra {
  flushDraw: number;
  nutFlushDraw: number;
  oesd: number;
  gutshot: number;
  comboDraw: number;
  twoOvercards: number;
  overpair: number;
  topPair: number;
  secondPairPlus: number;
  pairKicker: number;
  overcardsToPair: number;
}

function heroExtraFeatures(
  hole: [CardId, CardId],
  board: CardId[]
): HeroExtra {
  const z: HeroExtra = {
    flushDraw: 0, nutFlushDraw: 0, oesd: 0, gutshot: 0, comboDraw: 0,
    twoOvercards: 0, overpair: 0, topPair: 0, secondPairPlus: 0,
    pairKicker: 0, overcardsToPair: 0,
  };
  if (board.length < 3) return z;

  const hr = [rankOf(hole[0]), rankOf(hole[1])];
  const hs = [suitOf(hole[0]), suitOf(hole[1])];
  const br = board.map(rankOf);
  const bs = board.map(suitOf);
  const topBoard = Math.max(...br);
  const toCome = 5 - board.length;
  const cat = Math.floor(evaluateHand([hole[0], hole[1], ...board]) / 1_000_000);

  // Flush draw: a suit where hero contributes and hole+board total exactly 4.
  if (toCome > 0 && cat < HAND_CATEGORY.FLUSH) {
    for (let s = 0; s < 4; s++) {
      const holeS = hs.filter((x) => x === s).length;
      const boardS = bs.filter((x) => x === s).length;
      if (holeS >= 1 && holeS + boardS === 4) {
        z.flushDraw = 1;
        if (hr.some((r, i) => hs[i] === s && r === 12)) z.nutFlushDraw = 1;
      }
    }
  }

  // Straight-draw outs that USE a hero card.
  if (toCome > 0 && cat < HAND_CATEGORY.STRAIGHT) {
    const present = new Set<number>([...hr, ...br]);
    const holeSet = new Set<number>(hr);
    const has = (r: number) => (r === -1 ? present.has(12) : present.has(r));
    const holeHas = (r: number) => (r === -1 ? holeSet.has(12) : holeSet.has(r));
    let outs = 0;
    for (let o = 0; o < 13; o++) {
      if (present.has(o)) continue;
      present.add(o);
      let found = false;
      for (let lo = -1; lo <= 8 && !found; lo++) {
        let ok = true;
        let usesHole = false;
        let usesOut = false;
        for (let k = 0; k < 5; k++) {
          const r = lo + k;
          if (!has(r)) {
            ok = false;
            break;
          }
          if (r === o) usesOut = true;
          if (holeHas(r)) usesHole = true;
        }
        if (ok && usesOut && usesHole) found = true;
      }
      present.delete(o);
      if (found) outs++;
    }
    if (outs >= 2) z.oesd = 1;
    else if (outs === 1) z.gutshot = 1;
  }
  z.comboDraw = z.flushDraw && (z.oesd || z.gutshot) ? 1 : 0;

  // Pair quality.
  const pocket = hr[0] === hr[1];
  if (cat === HAND_CATEGORY.PAIR) {
    if (pocket) {
      if (hr[0] > topBoard) z.overpair = 1;
      else z.secondPairPlus = 1;
    } else {
      const matched = hr.find((r) => br.includes(r));
      const kicker = hr.find((r) => !br.includes(r));
      if (matched === topBoard) z.topPair = 1;
      else z.secondPairPlus = 1;
      if (kicker !== undefined) z.pairKicker = kicker / 12;
      if (matched !== undefined) z.overcardsToPair = br.filter((r) => r > matched).length / 5;
    }
  } else if (
    cat === HAND_CATEGORY.HIGH_CARD &&
    !pocket &&
    Math.min(hr[0], hr[1]) > topBoard
  ) {
    z.twoOvercards = 1;
  }
  return z;
}

export function encodeSpot(spot: Spot): Float32Array {
  const f = new Float32Array(FEATURE_DIM);
  const [c1, c2] = spot.holeCards;
  const r1 = rankOf(c1);
  const r2 = rankOf(c2);
  const s1 = suitOf(c1);
  const s2 = suitOf(c2);
  const high = Math.max(r1, r2);
  const low = Math.min(r1, r2);

  let heroCat: number = HAND_CATEGORY.HIGH_CARD;
  if (spot.board.length >= 3) {
    const rank = evaluateHand([c1, c2, ...spot.board]);
    heroCat = Math.floor(rank / 1_000_000);
  }
  for (let i = 0; i < CATEGORY_COUNT; i++) f[i] = heroCat === i ? 1 : 0;

  f[9] = deterministicEquity(spot.holeCards, spot.board);

  f[10] = high / 12;
  f[11] = low / 12;
  f[12] = s1 === s2 ? 1 : 0;
  f[13] = r1 === r2 ? 1 : 0;
  f[14] = high >= 8 && low >= 8 ? 1 : 0;
  f[15] = (high - low) / 12;

  const suitCounts = [0, 0, 0, 0];
  const rankCounts = new Map<number, number>();
  for (const c of spot.board) {
    suitCounts[suitOf(c)]++;
    const r = rankOf(c);
    rankCounts.set(r, (rankCounts.get(r) || 0) + 1);
  }
  const maxSuit = Math.max(0, ...suitCounts);
  const monotone = maxSuit >= 3 ? 1 : 0;
  const twoTone = maxSuit === 2 ? 1 : 0;
  const paired = [...rankCounts.values()].some((v) => v >= 2) ? 1 : 0;
  f[16] = monotone;
  f[17] = twoTone;
  f[18] = paired;
  f[19] = spot.board.length ? maxSuit / 5 : 0;

  const distinct = [...rankCounts.keys()].sort((a, b) => a - b);
  let steps = 0;
  for (let i = 1; i < distinct.length; i++) {
    if (distinct[i] - distinct[i - 1] === 1) steps++;
  }
  f[20] = steps / 4;
  const topRank = distinct.length ? distinct[distinct.length - 1] : 0;
  f[21] = topRank / 12;
  let broadwayOnBoard = 0;
  for (const c of spot.board) if (rankOf(c) >= 8) broadwayOnBoard++;
  f[22] = broadwayOnBoard / 5;

  f[23] = spot.street === "flop" ? 1 : 0;
  f[24] = spot.street === "turn" ? 1 : 0;
  f[25] = spot.street === "river" ? 1 : 0;

  f[26] = spot.heroPos === "IP" ? 1 : 0;
  f[27] = spot.facingBet ? 1 : 0;
  f[28] = clamp(spot.toCallFrac, 0, 3);
  f[29] = clamp(spot.offeredSizeFrac, 0, 3);
  f[30] = Math.log1p(clamp(spot.offeredSizeFrac, 0, 3));
  f[31] = spot.threeBetPot ? 1 : 0;

  f[ACTION_MASK_OFFSET + 0] = spot.canFold ? 1 : 0;
  f[ACTION_MASK_OFFSET + 1] = spot.canCheck ? 1 : 0;
  f[ACTION_MASK_OFFSET + 2] = spot.canCall ? 1 : 0;
  f[ACTION_MASK_OFFSET + 3] = spot.canBet ? 1 : 0;
  f[ACTION_MASK_OFFSET + 4] = spot.canRaise ? 1 : 0;

  const hx = heroExtraFeatures(spot.holeCards, spot.board);
  f[37] = hx.flushDraw;
  f[38] = hx.nutFlushDraw;
  f[39] = hx.oesd;
  f[40] = hx.gutshot;
  f[41] = hx.comboDraw;
  f[42] = hx.twoOvercards;
  f[43] = hx.overpair;
  f[44] = hx.topPair;
  f[45] = hx.secondPairPlus;
  f[46] = hx.pairKicker;
  f[47] = hx.overcardsToPair;

  f[48] = spot.isPreflopAggressor ? 1 : 0;
  f[49] = spot.facedRaiseThisStreet ? 1 : 0;
  f[50] = Math.min(1, (spot.streetBetCount ?? 0) / 3);

  return f;
}

export function legalMaskFromFeatures(
  f: Float32Array | number[],
  offset = 0
): number[] {
  const o = offset + ACTION_MASK_OFFSET;
  return [f[o], f[o + 1], f[o + 2], f[o + 3], f[o + 4]];
}
