// ============================================================
// Pure-TS forward pass for the distilled postflop policy.
//
// Loads weights from model.ts (base64 Float32, generated by ml/train.py in
// the gto-poker-overlay repo), standardizes the shared encodeSpot() features
// with the saved train mean/std, runs a 2-hidden-layer ReLU MLP, softmaxes,
// then masks to LEGAL actions and renormalizes.
//
// Held-out TEST action-match accuracy (legal-masked): 0.8448
// Bet-size head val accuracy: 0.9240
// ============================================================

import { MODEL } from "./model";
import {
  encodeSpot,
  Spot,
  FEATURE_DIM,
  ACTIONS,
  ActionClass,
  legalMaskFromFeatures,
  SIZE_BUCKET_FRACS,
} from "./features";

// Browser fallback only; Node (the server) uses Buffer.
declare function atob(data: string): string;

function b64ToF32(b64: string): Float32Array {
  let bytes: Uint8Array;
  if (typeof Buffer !== "undefined") {
    const buf = Buffer.from(b64, "base64");
    bytes = new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
  } else {
    const bin = atob(b64);
    bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  }
  // Copy so the Float32Array never aliases a larger pooled buffer.
  const copy = new Uint8Array(bytes.length);
  copy.set(bytes);
  return new Float32Array(copy.buffer);
}

interface LoadedModel {
  W1: Float32Array; b1: Float32Array;
  W2: Float32Array; b2: Float32Array;
  W3: Float32Array; b3: Float32Array;
  dims: Record<string, number[]>;
  mean: Float32Array;
  std: Float32Array;
  sW1: Float32Array; sb1: Float32Array;
  sW2: Float32Array; sb2: Float32Array;
  sW3: Float32Array; sb3: Float32Array;
  sizeDims: Record<string, number[]>;
}

let MODEL_CACHE: LoadedModel | null = null;

function getModel(): LoadedModel {
  if (MODEL_CACHE) return MODEL_CACHE;
  const w = MODEL.weights;
  const s = MODEL.sizeWeights;
  MODEL_CACHE = {
    W1: b64ToF32(w.W1), b1: b64ToF32(w.b1),
    W2: b64ToF32(w.W2), b2: b64ToF32(w.b2),
    W3: b64ToF32(w.W3), b3: b64ToF32(w.b3),
    dims: MODEL.dims,
    mean: b64ToF32(MODEL.mean),
    std: b64ToF32(MODEL.std),
    sW1: b64ToF32(s.W1), sb1: b64ToF32(s.b1),
    sW2: b64ToF32(s.W2), sb2: b64ToF32(s.b2),
    sW3: b64ToF32(s.W3), sb3: b64ToF32(s.b3),
    sizeDims: MODEL.sizeDims,
  };
  return MODEL_CACHE;
}

function denseRelu(
  x: Float32Array,
  W: Float32Array,
  b: Float32Array,
  din: number,
  dout: number
): Float32Array {
  const out = new Float32Array(dout);
  for (let o = 0; o < dout; o++) {
    let acc = b[o];
    for (let i = 0; i < din; i++) acc += x[i] * W[i * dout + o];
    out[o] = acc > 0 ? acc : 0;
  }
  return out;
}

function dense(
  x: Float32Array,
  W: Float32Array,
  b: Float32Array,
  din: number,
  dout: number
): Float32Array {
  const out = new Float32Array(dout);
  for (let o = 0; o < dout; o++) {
    let acc = b[o];
    for (let i = 0; i < din; i++) acc += x[i] * W[i * dout + o];
    out[o] = acc;
  }
  return out;
}

export function forwardLogits(raw: Float32Array | number[]): number[] {
  const m = getModel();
  const x = new Float32Array(FEATURE_DIM);
  for (let i = 0; i < FEATURE_DIM; i++) x[i] = (raw[i] - m.mean[i]) / m.std[i];
  const h1Dim = m.dims.b1[0];
  const h2Dim = m.dims.b2[0];
  const outDim = m.dims.b3[0];
  const a1 = denseRelu(x, m.W1, m.b1, FEATURE_DIM, h1Dim);
  const a2 = denseRelu(a1, m.W2, m.b2, h1Dim, h2Dim);
  return Array.from(dense(a2, m.W3, m.b3, h2Dim, outDim));
}

export interface PostflopPrediction {
  probs: Record<ActionClass, number>;
  action: ActionClass;
}

export function predictPostflop(spot: Spot): PostflopPrediction {
  const m = getModel();
  const raw = encodeSpot(spot);
  const x = new Float32Array(FEATURE_DIM);
  for (let i = 0; i < FEATURE_DIM; i++) x[i] = (raw[i] - m.mean[i]) / m.std[i];

  const h1Dim = m.dims.b1[0];
  const h2Dim = m.dims.b2[0];
  const outDim = m.dims.b3[0];

  const a1 = denseRelu(x, m.W1, m.b1, FEATURE_DIM, h1Dim);
  const a2 = denseRelu(a1, m.W2, m.b2, h1Dim, h2Dim);
  const logits = dense(a2, m.W3, m.b3, h2Dim, outDim);

  const mask = legalMaskFromFeatures(raw);
  for (let i = 0; i < outDim; i++) {
    if (mask[i] < 0.5) logits[i] = -Infinity;
  }

  let max = -Infinity;
  for (const v of logits) if (v > max) max = v;
  let sum = 0;
  const exp = new Float32Array(outDim);
  for (let i = 0; i < outDim; i++) {
    const e = logits[i] === -Infinity ? 0 : Math.exp(logits[i] - max);
    exp[i] = e;
    sum += e;
  }

  const probs = {} as Record<ActionClass, number>;
  let bestI = 0;
  let bestP = -1;
  for (let i = 0; i < ACTIONS.length; i++) {
    const p = sum > 0 ? exp[i] / sum : mask[i] > 0.5 ? 1 : 0;
    probs[ACTIONS[i]] = p;
    if (p > bestP) {
      bestP = p;
      bestI = i;
    }
  }

  return { probs, action: ACTIONS[bestI] };
}

export interface BetSizePrediction {
  bucket: number;
  fraction: number;
}

export function predictBetSize(spot: Spot): BetSizePrediction {
  const m = getModel();
  const raw = encodeSpot(spot);
  const x = new Float32Array(FEATURE_DIM);
  for (let i = 0; i < FEATURE_DIM; i++) x[i] = (raw[i] - m.mean[i]) / m.std[i];

  const h1 = m.sizeDims.b1[0];
  const h2 = m.sizeDims.b2[0];
  const out = m.sizeDims.b3[0];
  const a1 = denseRelu(x, m.sW1, m.sb1, FEATURE_DIM, h1);
  const a2 = denseRelu(a1, m.sW2, m.sb2, h1, h2);
  const logits = dense(a2, m.sW3, m.sb3, h2, out);

  let bestI = 0;
  let bestV = -Infinity;
  for (let i = 0; i < out; i++) {
    if (logits[i] > bestV) {
      bestV = logits[i];
      bestI = i;
    }
  }
  const fraction =
    SIZE_BUCKET_FRACS[bestI] ?? SIZE_BUCKET_FRACS[SIZE_BUCKET_FRACS.length - 1];
  return { bucket: bestI, fraction };
}

export const MODEL_ACCURACY = MODEL.accuracy;
export const SIZE_ACCURACY = MODEL.sizeAccuracy;
